### ISSUE TITLE
Shop archive

### ISSUE THREAD

**Issue by CiaranChris** [briggySmalls/skin-deep-server#118]
Is it this page? 
![screen shot 2018-11-28 at 11 32 24](https://user-images.githubusercontent.com/29028655/49149171-50263c00-f301-11e8-8809-4623fd135af9.png)
or 
![screen shot 2018-11-28 at 11 32 48](https://user-images.githubusercontent.com/29028655/49149181-5a483a80-f301-11e8-93b2-56e7f50af283.png)

I think if possible could we get the button and price to sit next to each other like on the single product page
 
![screen shot 2018-11-28 at 11 33 31](https://user-images.githubusercontent.com/29028655/49149301-a4c9b700-f301-11e8-9657-0f373523cac0.png)

Button Colour to change but will get back to you on this

**Comment by briggySmalls** [comment]
Yeah sure. can do
