### ISSUE TITLE
Make menu text stand out

### ISSUE THREAD

**Issue by briggySmalls** [briggySmalls/skin-deep-server#141]
From Anu's review:

> Font and colour of categories on main menu needs to be bolder and black rahter than grey.

**Comment by briggySmalls** [comment]
Yessir!

**Comment by briggySmalls** [comment]
will help with contrast issue in #88

**Comment by CiaranChris** [comment]
DAMN IT!!! :') 

With the banner and then the 'Article' page title underneath, it's so busy 😅

With the menu, goes darker,
<img width="337" alt="screenshot 2018-12-16 at 12 47 05" src="https://user-images.githubusercontent.com/29028655/50053665-e6939380-0130-11e9-9e30-608ac32f4fb7.png">

If that blue
<img width="1169" alt="screenshot 2018-12-16 at 12 50 02" src="https://user-images.githubusercontent.com/29028655/50053675-1fcc0380-0131-11e9-9cd5-8e8ca5953566.png">
 changed to maybe the orange in the menu... What do you think? it seemed to help with the nav on the last site 
<img width="1172" alt="screenshot 2018-12-16 at 12 49 01" src="https://user-images.githubusercontent.com/29028655/50053682-3bcfa500-0131-11e9-844c-c0ff9a865117.png">
<img width="1169" alt="screenshot 2018-12-16 at 12 49 34" src="https://user-images.githubusercontent.com/29028655/50053683-3bcfa500-0131-11e9-9d40-a0fae2e225da.png">
<img width="334" alt="screenshot 2018-12-16 at 12 49 41" src="https://user-images.githubusercontent.com/29028655/50053684-3c683b80-0131-11e9-8441-242039f7643c.png">

Though it makes me want to provide an accent colour for that. Is it possible to build a field that the editorial team could then if they wanted change the colour of the menu highlight say to match the print colours? just a thought.

**Comment by briggySmalls** [comment]
Yeah, can set orange no problem. I also think it is doable to make the colour configurable too yeah.

**Comment by briggySmalls** [comment]
I think I'll start with just implementing the colours. Admin configurable will be v2

**Comment by briggySmalls** [comment]
Converting that [colour to HSL](https://contrast-ratio.com/#hsl%2831%2C%20100%25%2C%2052%25%29-on-rgb%28248%2C%20249%2C%20250%29) allows increasing the tinting/shading of the tone.

These combinations would fix us:
- Minimum tinting
  - Increase the text size in the heading to 1.2rem (14pt)
  - Set sub-menu bold too
  - Set the colour to `hsl(31, 100%, 43%)`
- Minimum sizing changes
  - Set the colour to `hsl(31, 100%, 34%)`
- Mix
  - Increase the text size in the heading to 1.5rem (24px)
  - `hsl(31, 100%, 43%)`

Can test how this looks by adding a new css style:
```css
nav.navbar {
    font-size: 1.2rem; /* or 1.5rem */
}
```
And updating existing style
```css
nav.navbar .navbar-nav .active>.nav-link {
    color: hsl(31, 100%, 34%) /* or hsl(31, 100%, 43%) */
}
```

**Comment by CiaranChris** [comment]
Happy to give this a go. 

Didn't realise hsl gives your finer control. Thanks 😁

**Comment by briggySmalls** [comment]
Tbh I am inclined to agree with you and keep things how they are. But have a look at those three options that are compliant. If one of them isn't horrible to you then may as well throw it in. But I'm not too worried about this one.

**Comment by CiaranChris** [comment]
_Mix
Increase the text size in the heading to 1.5rem (24px)
hsl(31, 100%, 43%)_

This option please. I think keeping it consistent across both is best. 

Happy to implement these.

Is it possible to have the current colour on the dark theme only?
