### ISSUE TITLE
Link colour on dark theme

### ISSUE THREAD

**Issue by briggySmalls** [briggySmalls/skin-deep-server#142]
Anu has rightly pointed out that the blue hyperlink colour on a dark background is no good:

> i am not a fan of the blue font on black background for text that is linked

**Comment by CiaranChris** [comment]
Will find a hex code for you so we can change it. 

I think a lighter and more pastel blue across all hyperlinks and maybe they change to a subtler more pastel purple.

**Comment by briggySmalls** [comment]
Yep, it is definitely possible. So if you find some nice colours I can put them in easy :)

**Comment by briggySmalls** [comment]
I spent some time looking at this in #45.

All of your suggestions horrify me 😱 

## Visited links

Regarding visited links, it is [super necessary](https://www.nngroup.com/articles/change-the-color-of-visited-links/). It is number 3 on Nielsen's [Top 10 Mistakes in Web Design](https://www.nngroup.com/articles/top-10-mistakes-web-design/). If you read about this anywhere everyone concludes the same thing. Users need to know where they've been.

## Link colours

Absolutely everyone agrees [1] [2] [3], EVEN more so than on visited links, that links must be _one consistent colour_. The actual chosen colour is up for debate, although it has been demonstrated time and time again that blue links are overwhelmingly more intuitive to users than any other colour.

[1]:https://ux.stackexchange.com/questions/2278/should-hyperlinks-be-blue/2297#2297
[2]: https://usabilitygeek.com/hyperlink-usability-guidelines-usable-links/
[3]: https://baymard.com/blog/formatting-links-for-usability

We have removed underlining, which I agreed with because we stuck with the standard blue. which [can be OK](https://www.nngroup.com/articles/guidelines-for-visualizing-links/), but:

> Exception: underlining is essential if you use link colors such as reds or greens, which cause problems for users with common forms of color-blindness.

**Comment by CiaranChris** [comment]
LOL!!!! See, I just wanted to ask. 

I'm at ease with a blue and a softer purple. This to me seems like a nice combo and give. what you think? also against the black it pops a little better.

#5bb4ee - blue
#c06afa - purple 

Also had a feeling about things being in red.

**Comment by briggySmalls** [comment]
I'll go out on a limb here and say I think we can change the link colour for the dark theme? The perception will be that the same colours would appear different anyway I would have thought 🤔 

We'd never get good contrast against both black and white with the same colour.

The two colours you just supplied are great for the dark theme. I just checked on a [contrast checker](https://contrast-ratio.com/#%235bb4ee-on-white). Maybe find another pair for the white background?

**Comment by briggySmalls** [comment]
@ciaranchris, can I consider this fixed?

**Comment by CiaranChris** [comment]
YES! This is fixed. I don't think i'm going to find these colours
