### ISSUE TITLE
Update 'About us' page

### ISSUE THREAD

**Issue by briggySmalls** [briggySmalls/skin-deep-server#143]
From Anu:

> it would be great if we had our photos or a photo of the whole team on this page - @sylviasuli what do you think?

**Comment by CiaranChris** [comment]
Sylvia thing.

could we use a place holder for where the team photo will go. I still really want to use headshots but will ask.

**Comment by briggySmalls** [comment]
Are you saying that while they make a decision can we put a placeholder image in?

**Comment by CiaranChris** [comment]
Yessir! can we use this one for now.

![image](https://user-images.githubusercontent.com/29028655/49744244-44892c80-fc94-11e8-87ac-55763a99370d.png)


Sylvia was asked to take team portraits but with everyones schedules its proving a little difficult atm and i think has dropped off the radar.

**Comment by briggySmalls** [comment]
We don't think these pictures are going to be taken. Easier to close this.
