### ISSUE TITLE
Improve submissions page

### ISSUE THREAD

**Issue by briggySmalls** [briggySmalls/skin-deep-server#144]
From Anu:

> Are there ways we can make this page more exciting. Perhaps not, but wanted to ask the question!

**Comment by CiaranChris** [comment]
I will mock this up. 

Is there a field we could have where if people wanted to upload their work directly to the site, drag and drop, or simple upload button, that they could use and it would notify the relevant people that theres a new submission.

I think currently the work gets sent in via email, but i suppose they do get a change to vet the submission...

Just a thought

**Comment by briggySmalls** [comment]
Can you ask Anu if they would value this feature?

I haven't done much thinking about it, but my guess is that email servers do all sorts of security scanning on attachments. I'm a bit nervous of the security implications.

**Comment by CiaranChris** [comment]
You're right. I completely forgot about the security side of something like that.

If I could have a place holder image at the top with a space for text blurb and perhaps a gallery widget. maybe we could show examples there of how we've used the work and that entice more submissions.

**Comment by briggySmalls** [comment]
So everything you describe is not a software change, but one that is performed in the admin side of the site.

I guess we've never discussed this particularly, but I see my role as making theme/plugins that allow editors and designers to make things how they want them.

So I regard this sort of job as something that should be done by either yourself, or one of the site maintainers. So can we chalk this one up as one I'll show you how to do? The new 'editorial' label is attached to anything I think that falls into this category of work.

**Comment by CiaranChris** [comment]
I thought that might have been the case. 😅

Yes please. I have a feeling a lot more of these types of things will come up

**Comment by briggySmalls** [comment]
Closing this for the moment as nobody has made any noise on this for a while.
