### ISSUE TITLE
Separate categories more distinctly

### ISSUE THREAD

**Issue by briggySmalls** [briggySmalls/skin-deep-server#148]
From Anu's review:

> Category tags underneath article thumbnail, need to be separated by a comma or dash or something cos atm the category names run straight on from each other which is weird eg. Activism Skin Deep Meets (for Anna Himali Howard interview)

**Comment by CiaranChris** [comment]
Commas please. black, same weight as category text and not a part of the links please?

**Comment by briggySmalls** [comment]
Great. on it sarge 👮
