### ISSUE TITLE
Increase image width

### ISSUE THREAD

**Issue by briggySmalls** [briggySmalls/skin-deep-server#150]
From Anu's review:

> image - should is stretch across whole page or are there meant to be white spaces on each end of the image?

Is this desired?

**Comment by CiaranChris** [comment]
Could the image be full screen up to a point where the window is wider and then the white sides appear? 

I think we changed it to always when I asked if the body could have an inset

**Comment by briggySmalls** [comment]
I'll have a look. I suppose the breakpoint would be 1200px
