### ISSUE TITLE
Text styling across site

### ISSUE THREAD

**Issue by CiaranChris** [briggySmalls/skin-deep-server#154]
b-list text styling

<img width="1496" alt="screenshot 2018-12-13 at 23 32 53" src="https://user-images.githubusercontent.com/29028655/49974264-4a02a300-ff30-11e8-89b9-f2ba4e51d3c7.png">
<img width="1501" alt="screenshot 2018-12-13 at 23 33 49" src="https://user-images.githubusercontent.com/29028655/49974285-5ab31900-ff30-11e8-80b5-ff5c521af924.png">

could the categories menu be taken up a weight please - its called normal

**Comment by CiaranChris** [comment]
<img width="1605" alt="screenshot 2018-12-13 at 23 49 00" src="https://user-images.githubusercontent.com/29028655/49974647-36f0d280-ff32-11e8-8d33-c8840a9146a4.png">
on article page could the category, date and written by be taken up to the next weight in the font family, both bold please. ☺️

**Comment by briggySmalls** [comment]
Currently I have:
- Sub menu
- Event details
- 'written by' & Author
- Product price

all explicitly designated to be 'lighter'. I guess because we decided that before.

Do you want all of these taken up to normal?

**Comment by CiaranChris** [comment]
Event details - is this the details on the events article page? 
<img width="616" alt="screenshot 2018-12-14 at 00 34 47" src="https://user-images.githubusercontent.com/29028655/49975964-1461b800-ff38-11e8-82c7-92ab0b7dd7b7.png">
if so, yes please take those to normal. It should help with making the details more prominent 

I've also noticed we don't currently have an image caption style nor a field for putting in 'image by' for the feature image. I am happy not to have the 'image by' field for the feature image and have the image caption style match the styling of 'written by' style and sit directly underneath the images as it could for then images within articles.

**Comment by briggySmalls** [comment]
Ah yeah, the old captions. Created an issue to track this #155
