### ISSUE TITLE
Rename 'back to basics' articles

### ISSUE THREAD

**Issue by briggySmalls** [briggySmalls/skin-deep-server#159]
The back to basics articles have the category name 'baked in' to their titles. This is leading to the category being written all over the place.

Now that we have a good way of displaying categories this text should be removed from the titles.

This is a carry over from #79.

**Comment by CiaranChris** [comment]
Can jump on this. Just say if it's ok to 😁

**Comment by briggySmalls** [comment]
Don't worry, I've done it.
