### ISSUE TITLE
Add/port mailing list

### ISSUE THREAD

**Issue by briggySmalls** [briggySmalls/skin-deep-server#21]
The current website can display a popup to sign up to a mailchimp mailing list.

Somewhere on the site there will need to be a similar call-to-action.

**Comment by briggySmalls** [comment]
@CiaranChris do you want this to look how you drew it on your first mock up?

**Comment by briggySmalls** [comment]
Discussion of adding a dismissible prompt for the mailing list.

![image from ios compressed](https://user-images.githubusercontent.com/11054133/48589708-a2944f80-e934-11e8-97ba-5eb707882796.jpg)

**Comment by briggySmalls** [comment]
What should this link to?

Maybe the same content as shown in the current site's popup, but on a new page (I seem to remember you want to ditch the popup 👍 )?

Alternatively it could just navigate to the [mailchimp signup form](https://skindeepmag.us12.list-manage.com/subscribe?u=52a202f000bbf7fb27d49f694&id=943ad6701c) on a different site, but I suppose that is suboptimal.

**Comment by briggySmalls** [comment]
I was going to use a [dismissable alert](https://getbootstrap.com/docs/4.1/components/alerts/#dismissing) from bootstrap. 

Note that [modals/popups](https://getbootstrap.com/docs/4.1/components/modal/#live-demo) are available.

**Comment by CiaranChris** [comment]
Dismissable alert: Into! Need to figure out when it would appear for the user.  

Happy to implement modals/popup, can this be a user generate action? So the user would click on the icon then the pop up would appear.

Yes please to having a widget on the home page. Is it possible to have a field where the user could submit their email address? I think it could fit quite nicely under events

a little like jacobin's, theirs is at the bottom of the page though... weird 

<img width="1210" alt="screenshot 2018-12-18 at 17 44 20" src="https://user-images.githubusercontent.com/29028655/50172374-d1fbfa80-02ec-11e9-8202-c27e991146a7.png">

**Comment by briggySmalls** [comment]
So we need to display the signup form somewhere. Currently this comprises 'name' and 'email' fields. We'd need to check with Anu if we wanted [to drop the 'name' field](https://ux.stackexchange.com/questions/102675/should-i-remove-name-field-in-my-newsletter-sign-up-form) from signup.

The question is where to show it to the user. Some high-level approaches are:

| Option | Example | Advantages | Disadvantages |
| -- | -- | -- | -- |
| Display in a common place on all pages | Jacobin's is in the footer | Consistency | Can be difficult to fit, resulting in being placed somewhere hard to find |
| Create a dedicated location and direct users there | Create a 'signup' page, display link in header, on home page, etc. | Consistency. Plenty of space for form. Links can be varied and neat/small making most pages 'uncluttered'. Simple. | Higher friction - multiple user steps / required navigating away from current content |
| Have multiple different ways to display | Block on homepage, signup in footer, signup in dismissable prompt, signup in popup | Can use more/less space according to context | Inconsistent. Multiple paths can be confusing? |

Reading your comment, can I read back to you what I understood to make sure I got this right:

- Signup 'block' displayed on home page, between what is currently the 'events' and 'videos' blocks
- Dismissable alert displayed on content pages (e.g. articles, events, products, etc.). Did you imagine this to contain the fields and a 'confirm' button?
- What would the popup do? Something like what happens on the current site (press email icon and popup shows)?

i.e. a form of the 3rd option?

Some thoughts:
- Initially I didn't understand your homepage suggestion, but I think I do now and I like it. Make a big bold block with signup fields and submit button in it.
- I had initially assumed the dismissible prompt would be like the WIRED example: a link to a separate page. I think this would make headaches about mobile easier. Displaying two fields, a prompt and submit button horizontally on mobile sounds difficult/impossible.
- However I see that making users change page will probably stop people signing up, so it would be desirable to make the form appear on the screen.

My solutions:
- Remove 'name' field so we can try fit a prompt, email field, and button
- Have a dismissable, collapsable form like [this example](https://www.bootply.com/ddByVLmsRo#)

**Comment by briggySmalls** [comment]
Anu says the name field isn't important, so I think it would be good to drop it?

**Comment by briggySmalls** [comment]
The paywall would use a customer database, not the mailchimp list. I doubt we'd pull across people's emails/names from there. So no need from there.

If they had already been using names, then we'd need a compelling reason to remove it. As it is they don't send personalised emails. That could be a suggestion? But only some of the users currently have a name. So 🤷‍♂️ I reckon we have a reason to drop it, and they don't have a reason to keep it.

**Comment by CiaranChris** [comment]
Good to know. 

Completely happy to drop it then. If they have no use for it then let's remove it 😄

**Comment by briggySmalls** [comment]
I've implemented the banner, but not the home page block. I'm not sure how to style this in a good way. Can you have a look at what I've done so far please?

Currently if a user dismisses the prompt, it should stay dismissed for a month, then it will come back. I took a punt at the behaviour. Some other obvious behaviours are:
1. Never reappear whilst browser holds state (this could theoretically be forever)
2. Reappear in a new 'session' - i.e. when a user next restarts the browser.

I can remove it from the home page once the block is implemented. Although I think I favour showing it on all pages (until the user dismisses it).

The biggest reason is that the block on the homepage will be an 'editors' decision, and so might be removed/moved to a different page. Therefore I feel like which pages the banner appears on would then need to be an editor's decision too. This would require a bit more work (although not much).

So initially I'm keen to just put it on all pages, and if it is important to disable it on the front page then in v2 to implement a UI for the editor to enable/disable on pages.

**Comment by briggySmalls** [comment]
Oop. Submit button looks a bit rubbish on mobile.

**Comment by briggySmalls** [comment]
Should probably dismiss banner when a user presses 'submit'. I think this is probably the best chance we have of knowing someone signed up and therefore no longer needs to see the banner.

**Comment by briggySmalls** [comment]
@CiaranChris would be great to get your opinion on the current banner and any suggestions for improvements

**Comment by briggySmalls** [comment]
Closing this as fixed for the time being. Improvements to the banner could be tracked in a new issue. The block for the homepage is tracked in #173
