### ISSUE TITLE
Add banner advert

### ISSUE THREAD

**Issue by briggySmalls** [briggySmalls/skin-deep-server#23]
It seems people are happy with the current banner/advert at the top of every screen.

The theme should be updated to allow setting this.

**Comment by briggySmalls** [comment]
@CiaranChris is this correct?

**Comment by CiaranChris** [comment]
YES PLEASEEEEE :D 

I thought it was something that came with every theme so never questioned it. Thank you

**Comment by briggySmalls** [comment]
Nope. It all requires elbow grease 💪

**Comment by briggySmalls** [comment]
From anu's review:

> I miss the banner that says ‘Movements Out Now’ :disappointed:
