### ISSUE TITLE
Escaping HTML in titles

### ISSUE THREAD

**Issue by briggySmalls** [briggySmalls/skin-deep-server#36]
I still can't work out the best approach for HTML in titles.

Sage outputs raw content, allowing javascript to be injected into the title.

I'd prefer not to do this, but then other harmless characters are escaped and then printed literally (e.g. em-dash or single quote).

**Comment by CiaranChris** [comment]
![screen shot 2018-10-07 at 19 32 35](https://user-images.githubusercontent.com/29028655/46585362-d774d300-ca67-11e8-801e-e6a0016ebb43.png)
is this what you mean?

**Comment by briggySmalls** [comment]
Exactly!

I can disable the escaping that causes that, but there is a theoretical security vulnerability that means of code was saved in the title it would be executed on page load.

It is fine if you trust editors to not malicious, which is a fair assumption in our case but i am supposed WordPress doesn't have a better answer for this...
