### ISSUE TITLE
How to style the home page

### ISSUE THREAD

**Issue by briggySmalls** [briggySmalls/skin-deep-server#39]
Currently the home page is a simple landing page, to identify the separate aspects of *Articles*, *Events* and *Products*.

The *Articles* page has a slider and sections of tiled articles. There is a _separate_ [latest articles](http://skindeepmag.tk/latest) archive that displays all articles.

It needs to be decided if this is how we want things to be. Some factors are:

- If we make a home page similar to the current _Articles_ page (sections of tiles), then the articles page will look less distinct (will people know they are on a different page?)
- We could replace the _Home_ page with the _Articles_ page, add some other sections (e.g. _Events_ and _Products_) and replace the _Articles_ page with the _latest articles_ archive (no sections). However this raises the question of where categories are listed.

**Comment by CiaranChris** [comment]
_•We could **replace the Home page with the Articles page**, add some other sections (e.g. Events and Products) and replace the **Articles page with the latest articles archive** (no sections). However this raises the question of where categories are listed._

This seems like the best idea. If possible then we could have a sub-menu under the main menu for the categories that appear only on the article page/s as discussed on the 07/10

**Comment by briggySmalls** [comment]
Great. good call.

Categories in menu is tracked by #44.

Closing this issue.
