### ISSUE TITLE
Paging navigation ("Older posts"/"Newer posts") styling

### ISSUE THREAD

**Issue by briggySmalls** [briggySmalls/skin-deep-server#43]
Currently the default paging navigation is displayed, with the following options stacked on top of each other:

- "Older posts"
- "Newer posts"

The wording, positioning and styling should be reviewed.

**Comment by briggySmalls** [comment]
Note this could be eliminated entirely if we went with infinite scroll.

**Comment by briggySmalls** [comment]
Jetpack's infinite scroll comes with two options:
- Scroll: when user approaches/scrolls near bottom of page, new posts load automatically
- Click: a 'Load more' button is displayed, allowing the user to control when new posts are loaded

The theme will [need to be updated](https://jetpack.com/support/infinite-scroll/#theme) to support this feature

**Comment by CiaranChris** [comment]
'Click: a 'Load more' button is displayed, allowing the user to control when new posts are loaded'

this is the option I would prefer to implement as I know on mobile trying to find a place where you've scrolled too is near impossible.

**Comment by briggySmalls** [comment]
This has now been requested by Anu too:
> When you click through seem more of a category - latest articles for example - you scroll down and you get optin to click older posts. Rather than taking you to another new page, I think it would be better if it was able to laod more artilces on teh same page. I find it confusing thinking about clickign to older or newer articles, rather than have them appear in chunks continually on the same page as you click older posts.
