### ISSUE TITLE
Does wordpress upload strange image sizes

### ISSUE THREAD

**Issue by briggySmalls** [briggySmalls/skin-deep-server#54]
@CiaranChris wonders if wordpress might change image sizes on upload.

For example juliacheng5.jpg is 2112 × 902 which seems odd.

It would be interesting to try to find the original and test whether this happens again on the new site.

**Comment by briggySmalls** [comment]
@CiaranChris, could you try find the original to this image if possible? Then I can have a look.

**Comment by CiaranChris** [comment]
![juliacheng5](https://user-images.githubusercontent.com/29028655/47372341-75f86980-d6e1-11e8-9e8f-028811b4b4d0.jpg)

Checked the original. Seems it was created at those dimensions... Super confusing.
