### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by CiaranChris** [briggySmalls/skin-deep-server#57]
Use of a custom font or set of fonts throughout the website

Ensuring that they load quickly for others and on other devices that these fonts aren't default to.

**Comment by briggySmalls** [comment]
So using a particular font (commercial) will probs require serving which I _think_ is slower/less robust than using google. I'll look into this and you see if your font has a lookalike on google.

**Comment by CiaranChris** [comment]
https://fonts.google.com/specimen/Oswald
https://fonts.google.com/specimen/Fira+Sans+Extra+Condensed
https://fonts.google.com/specimen/Michroma

I've started looking and was thinking we could try these for headlines and menu text. and perhaps we could use amiri for body copy - same as the old website. I've not dived as deep on body copy alternatives, though the current font is doing it's job.

https://fonts.google.com/?category=Serif&query=amir

**Comment by CiaranChris** [comment]
Sizing on Fonts:

Home page - 

Main Menu - Oswald, Semi bold
Sub Menu - Oswald, Semi bold

Bottom page menu - Oswald, Semi bold

Block headers - Oswald, Semi bold

Category - Oswald, Light 0.8rem
Headline - Oswald, Semi bold
Extract - Amiri, regular

On single article/ event

Category and date - Oswald, light 0.8rem
Headline - Oswald, semi bold
written by - Oswald, light
Image credits (to appear by images) - Oswald, light

**Comment by briggySmalls** [comment]
@CiaranChris still unsure of desired font. I'll add Oswald for now...

**Comment by briggySmalls** [comment]
I'm closing this for now as I've implemented the request.
Reopen the issue if you change your mind on fonts?

**Comment by briggySmalls** [comment]
Like Acme for card and article titles, but not for navbar or other titles

**Comment by CiaranChris** [comment]
Body text on single articles, single videos and single shop items appears as System Font default instead of [Amiri](https://fonts.google.com/specimen/Amiri). 

When using Amiri in the body, could we make the font slightly larger than the 1rem default. Perhaps somewhere around 1.05 - 1.1?

**Comment by briggySmalls** [comment]
From Anu's review:

> FONTS - I am not sure about the fonts for titles of articles on home page or the blurbs on home page. I dont think it looks that fresh! I prefer the font for the artilce body text. That seems more modern!

**Comment by briggySmalls** [comment]
I'm not sure I follow. You want Open Sans? Falling back to system sans serif if the connection to google fails?

**Comment by CiaranChris** [comment]
Sorry Sam. 

Yes, could we try Open Sans across the website, Menu, category, any where system font or the default is being used, can we retain the styling and weights? 

Could we please Acme where it is?

deleted the comment I was referring to.

**Comment by CiaranChris** [comment]
Whoop!!!! Thank you.

This was my thought to, perhaps after a couple of weeks use we can see what the team are using and cull accordingly.

I wish there was a way to preview font changes without you having to tweak code every time. 

On the cards, could we replace the Amiri with Open Sans please? I think that was one of Anu's comments.

<img width="362" alt="screenshot 2018-12-13 at 10 49 29" src="https://user-images.githubusercontent.com/29028655/49933892-cc557d80-fec4-11e8-9d94-876ea976f448.png">

**Comment by briggySmalls** [comment]
Ah good point. I'll do that tonight.

In terms of previewing, this looks like it was do the business https://www.google.com/url?sa=t&source=web&rct=j&url=https://chrome.google.com/webstore/detail/google-font-previewer-for/engndlnldodigdjamndkplafgmkkencc%3Fhl%3Den&ved=2ahUKEwiuhoKC-JzfAhUGEVAKHcI-D1cQFjACegQIChAB&usg=AOvVaw0qjlrz6d2aLH2JKpsA7znb&cshid=1544708644964

**Comment by CiaranChris** [comment]
This tool!!!!! thank you
