### ISSUE TITLE
Event details

### ISSUE THREAD

**Issue by CiaranChris** [briggySmalls/skin-deep-server#60]
Display event details clearer, time date. 

![screen shot 2018-10-07 at 19 28 37](https://user-images.githubusercontent.com/29028655/46585334-8cf35680-ca67-11e8-9ada-4e58e68053a5.png)

**Comment by briggySmalls** [comment]
It would be great to get an idea how you'd like this to look @CiaranChris

**Comment by CiaranChris** [comment]
There will be a mock-up coming your way this week.

**Comment by CiaranChris** [comment]
![sd_events_v1](https://user-images.githubusercontent.com/29028655/48029753-ea51f480-e146-11e8-88d9-1741fee0dec1.png)

So was hoping that it might be possible to use icons on the events page next to the time, date and location, allowing for quicker glance at the information?

Would it be possible to turn the location into a live link that would show the loaction in google maps or whichever, if the event has been set up correctly?

**Comment by CiaranChris** [comment]
Google are greedy bastards LOL! :')

**Comment by briggySmalls** [comment]
Sorry. I think I misread:

## Google maps
_embedding_ google in your own webpage costs money ([example](https://developers.google.com/maps/documentation/embed/guide)). Just having a link from the pin to google maps would be free i would guess.

## Sub-menu
I really like the sub-menu idea for events, and I've recently updated the menu to support this kind of thing. I've broken some other stuff (now articles sub-menu doesn't appear on a post) but I'm working on fixing that.

## Details on individual event
>Would it be possible to add the same, time, date, location to the specific events themselves, under the headline? maybe next to 'F see event on FB'

This should have been there already. When I re-sync the database i lose some changes. I've just re-saved the pages and the details get copied from facebook. Those details should be there now. Did you want them in the same horizontal style as on your mockup?

**Comment by briggySmalls** [comment]
K. I've had a first crack at the sub-menu. Something to think about is what to show when no events are found (try clicking on 'upcoming')

Also odd things are happening in the nav menu's highlighting (if you click 'past' then it also highlights 'all' mistakenly) which I'm working on...

**Comment by briggySmalls** [comment]
Superseded by #92
