### ISSUE TITLE
Shop as a grid

### ISSUE THREAD

**Issue by briggySmalls** [briggySmalls/skin-deep-server#61]
The shop should be simplified to look like a grid.

Further questions remain on whether we need to identify different categories, filter, or highlight out-of-stock products that should be answered once the grid approach has been implemented.

**Comment by briggySmalls** [comment]
See d7f9833b94b8717d675955052614abdbf8f5f596

**Comment by briggySmalls** [comment]
Regression introduced that displays wrong image size/aspect ratio for magazines.

**Comment by briggySmalls** [comment]
@CiaranChris I don't know what size images to display for the magazines in the shop. I had been making portrait images for them, but now they are all in the same grid I'm not sure how they should appear.

**Comment by CiaranChris** [comment]
Will send across a mock-up this week. Unsure of the actual size, Can show you tonight in PS.

**Comment by briggySmalls** [comment]
I like your suggestion of [Stack magazines](https://www.stackmagazines.com/shop/) and the way they place the portrait on a coloured background. Can add the funky rotation too!

**Comment by briggySmalls** [comment]
Background colour to be set by editor

**Comment by briggySmalls** [comment]
Fixed in 8cc52d998b99c64d167b16a9ded91ad16633b2f4
