### ISSUE TITLE
Swipe action (touch) to interact with slider

### ISSUE THREAD

**Issue by briggySmalls** [briggySmalls/skin-deep-server#66]
The slider/carousel is not easy to control on mobile.

The swipe action should spin the slider.

**Comment by CiaranChris** [comment]
I'm down to see that working.

**Comment by briggySmalls** [comment]
It is also [strongly recommended](https://www.nngroup.com/articles/mobile-carousels/)

**Comment by CiaranChris** [comment]
Is there any way to incorporate the swipe on mobile and retain the dots underneath? So that you have the ability to both swipe and tap through the article images in the slider. 

I think its enough and that people should understand... Could we keep the auto play feature though.

**Comment by briggySmalls** [comment]
Yeyeye. Swipe to come

On 6 Dec 2018 17:41, CiaranChris <notifications@github.com> wrote:

Is there any way to incorporate the swipe on mobile and retain the dots underneath? So that you have the ability to both swipe and tap through the article images in the slider.

I think its enough and that people should understand... Could we keep the auto play feature though.
