### ISSUE TITLE
Remove category image

### ISSUE THREAD

**Issue by briggySmalls** [briggySmalls/skin-deep-server#67]
_Originally posted by @briggySmalls in https://github.com/briggySmalls/skin-deep-server/issues/44#issuecomment-427678615_

**Comment by CiaranChris** [comment]
I'd rather not have them, I factored them in on the mock up but the more I think about them the less I want to integrate them into the design. Currently they serve as much purpose as a standard text category label.

**Comment by briggySmalls** [comment]
Alrighty! Can make that change easily
