### ISSUE TITLE
Mobile menu to large for fixed position

### ISSUE THREAD

**Issue by briggySmalls** [briggySmalls/skin-deep-server#70]
If the menu is too large (to many options) categories) some mobiles will not be able to view it all in the viewport. This hurts scrolling as the user needs to scroll through the whole page whilst it is occluded by the menu.

The menu should only be sticky on devices that have a large enough viewport.

**Comment by CiaranChris** [comment]
Two ways (so far) -

1 As is
![screen shot 2018-10-23 at 20 25 51](https://user-images.githubusercontent.com/29028655/47385585-61789900-d702-11e8-85f0-70257f305fa7.png)

2 we could have something like on the apple website; below the menu bar is an additional menu with side wards scroll for the items displayed from that category 

![screen shot 2018-10-23 at 20 23 04](https://user-images.githubusercontent.com/29028655/47385581-5e7da880-d702-11e8-8f9d-d5a464ba08ad.png)
