### ISSUE TITLE
Long lines exceed container

### ISSUE THREAD

**Issue by briggySmalls** [briggySmalls/skin-deep-server#71]
"remembering Somalia after the fact" had a long URL That does not line break, forcing the container width on my mobile

**Comment by CiaranChris** [comment]
If we could get editorial to supplement the full link with either a shortened version, using a tool like google url shortener - https://goo.gl/ or if they could use the link text to house the link address.

**Comment by briggySmalls** [comment]
Agreed. Closing as 'won't fix'
