### ISSUE TITLE
Add social sharing buttons

### ISSUE THREAD

**Issue by briggySmalls** [briggySmalls/skin-deep-server#77]
Add these to posts to share the post to articles.

Also we would like links to social media sites in the footer.

**Comment by briggySmalls** [comment]
From anu:

> Links / buttons to our Skin Deep  socials - where have these gone? I think these are important!

**Comment by briggySmalls** [comment]
@kerz_day, how should socials be styled? I can turn on some defaults for sharing a post, but there isn't anywhere for opening skin deep from menu bar etc.

**Comment by briggySmalls** [comment]
Oh, is it in footer we want it?

**Comment by CiaranChris** [comment]
These are now in the footer. Maybe there's a widget that can be style for the home page and then this could be replicated on articles. 

Could we try share buttons under the written by line please. Could they sit in a line together please.

https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview.html
https://developers.facebook.com/docs/plugins/share-button/ - could we get the FB one without the number of shares showing please 😅

kinda want to try an experiment, seeing if placing them towards the top generates more sharing or at the end of the article, if there's time

**Comment by briggySmalls** [comment]
So you only want FB and Twitter? Insta?

**Comment by briggySmalls** [comment]
Probably best to do this using jetpack.

Note to self: It won't show anywhere until its configured at wordpress.com, including designating which pages to display on.

@CiaranChris we'll show these sharing buttons on articles. Should I add them on pages, products, and events too? I suppose yes? But then I guess not archives? or the home page?

**Comment by briggySmalls** [comment]
Positioning of the sharing buttons [can be controlled](https://jetpack.com/support/sharing/)

**Comment by CiaranChris** [comment]
Yes please. I think we should add them on product and event pages. 

Agreed, not on the home and archive pages. 

Yes please. Only twitter and Fb. My concern with having a share to instagram is the crop of the image, and also not all our website header images are that visually strong. And the caption.

**Comment by briggySmalls** [comment]
Note that twitter give options to:
- Prefil the text of any proposed share, e.g. "Look what I found on Skin Deep"
- Provide hashtags, e.g. "#SkinDeep"

These might be useful? I suppose it might be nice to let editors control them, but I think that would be a v2 feature.

**Comment by briggySmalls** [comment]
> Can they sit in a line together

I'm going to assume this means horizontally? 😕

**Comment by briggySmalls** [comment]
Check this is how you want them

**Comment by CiaranChris** [comment]
Yes. This is perfect. Thank you 🙏🏾
