### ISSUE TITLE
Update logo(s)

### ISSUE THREAD

**Issue by briggySmalls** [briggySmalls/skin-deep-server#80]
The current staging site uses an old logo. I'm not sure if the current one is already uploaded to the website.

**Comment by CiaranChris** [comment]
Being reworked. I should really discuss this one with Sylvia

**Comment by CiaranChris** [comment]
![sd_lr_logo-04](https://user-images.githubusercontent.com/29028655/48646438-c0b78980-e9e0-11e8-9651-dcb136b3aabf.png)
Is it ok to take the logo from here? what dimensions...

**Comment by briggySmalls** [comment]
Can you supply a dark one please, as per https://github.com/briggySmalls/skin-deep-server/issues/18#issuecomment-436051836

**Comment by CiaranChris** [comment]
![sd_lr_logo-05_orange](https://user-images.githubusercontent.com/29028655/48796831-8c054400-ecf8-11e8-9430-b8610c42bcd3.png)
![sd_lr_logo-05_white](https://user-images.githubusercontent.com/29028655/48796833-8c9dda80-ecf8-11e8-8982-ca60f2a9bf45.png)

**Comment by briggySmalls** [comment]
This issue should also be used to track adding the 'dark' logo feature to the theme

**Comment by CiaranChris** [comment]
Could we put in the white logo for the dark themed pages please? 

![](https://user-images.githubusercontent.com/29028655/48796833-8c9dda80-ecf8-11e8-8982-ca60f2a9bf45.png)

**Comment by briggySmalls** [comment]
Yep. On my to do list

**Comment by briggySmalls** [comment]
Also requested by Anu:

> i dont think our logo looks good on teh dark grey background
