### ISSUE TITLE
Failing standard tests

### ISSUE THREAD

**Issue by briggySmalls** [briggySmalls/skin-deep-server#88]
Google's [lighthouse](https://developers.google.com/web/tools/lighthouse/) app can be run at https://lighthouse-dot-webdotdevsite.appspot.com/.

The website fails some standard tests:
- [x] Use HTTPS #86 
- [x] Use HTTP/2
- [ ] Meta description [SEO]
- [ ] Render-blocking asset loading #51 
- [x] Cache policy for static assets (e.g. css)
- [ ] Lazy load images
- [x] Add names to card links [accessibility]
- [x] Low contrast on bootstrap menus

These should be addressed, and as we converge upon a first release be re-tested.

**Comment by briggySmalls** [comment]
Lighthouse is available by just right-clicking in google

**Comment by CiaranChris** [comment]
Thank you for this Sam.

Just done my first report i suppose we want to see as much green as possible

**Comment by briggySmalls** [comment]
It's a fairly technical analysis of a website. Certainly anything in the 'performance' section is - it is mainly concerned with how fast the page loads. While it's fast, it's happy. While it's not, it suggests tricks you can do to reduce/delay the amount of data that needs to be downloaded to show the site.

Progressive Web App is not really relevant - it's aimed at web-based 'apps' that you could save to your desktop, open, and see something even if you are not connected to the net. It's meant to feel like a native app rather than a website. I usually turn this scan off.

Accessibility assesses how friendly your website is to all users. I think the largest number of rules are to do with making your website 'readable' to screen readers. Also things like good/clear text contrast (something failing on menu rn until it is solved with #141).

SEO is what it sounds like. I'm not too hot on what specifically needs to be done. But that's OK, we're doing OK. We're missing meta descriptions (solved with Yoast SEO, it's just like an 'excerpt' but for google) and I need to turn on a flag that says 'please include me in search engines' which is off because we are in development! I think accessibility and SEO have things in common: make something readable to a screen reader and it will also be readable to a robot.

**Comment by CiaranChris** [comment]
Ah, thank you.

I noticed this to. It's nice that too doesn't score to well either and i used this site daily :') 
<img width="858" alt="screenshot 2018-12-18 at 18 05 40" src="https://user-images.githubusercontent.com/29028655/50173721-310f3e80-02f0-11e9-8ca3-5f1461fea818.png">

Sam! you've done amazing!!! I guess SEO would be where we'd need an editorial hand

**Comment by briggySmalls** [comment]
Yeah. I _think_ the main thing we are missing SEO-wise is a meta description. This is something an editor would supply. At they same time they write the excerpt they'd write the meta description. Tbh I could consider setting the meta description to be the excerpt maybe...

**Comment by briggySmalls** [comment]
Note: the complaint "Ensure text remains visible during webfont load" is actually [not possible to fix with google fonts](https://github.com/google/fonts/issues/358).

Keep an eye on this in case it is resolved some time.

Alternatives are to host fonts ourselves (lose advantages of CDN, although it's debatable how many users will have cached these specific fonts). We [can't copy the css returned by google](https://css-tricks.com/dont-just-copy-the-font-face-out-of-google-fonts-urls/).

**Comment by briggySmalls** [comment]
Remaining things are:

## Performance
- The big one is images and their lazy loading. I've turned this on in jetpack, and I'm not keen to try implement this myself.
- Next is deferring static assets. This is where most of my performance work has been done and I've squeezed what I can.
- Caching. Will turn this on at the end. It should mitigate the warning about deferring static assets.
- Ensuring text remains visible during webfont load is [not possible with gfonts atm](https://github.com/briggySmalls/skin-deep-server/issues/88#issuecomment-448440393). An 'on hold' issue should be created to keep an eye on this.

Other diagnostics come and go, including 'minimize main-thread work' and 'reduce javascript execution time'. I _think_ Snipcart is a big offender here.

## Accessibility
- Text for slider link. Should be the post title. I actually wonder if we should always show the post title, even on mobile? What good is the image alone, does a user know it is an article?

## SEO
- Meta descriptions need supplying by editors. #123 is the software work required.
- Page is blocked from indexing on staging [automatically](https://github.com/briggySmalls/skin-deep-server/blob/65698746d361297817a37e04cde336890d4ba80c/site/web/app/mu-plugins/disallow-indexing.php) and will be removed for production.

**Comment by briggySmalls** [comment]
Note: there is no attempt currently to do any kind of code splitting in the theme. As a result the entire site's css is in one file, when only a subset will be used on each page (see layouts dir). This may well result in a smaller css file.

It would be straightforward to load different scripts using wordpress's conditionals (`is_archive`, `is_singular('product')`, etc.). So it might be worth some analysis (a quick check on how big the bundle for just a single article would be?

**Comment by briggySmalls** [comment]
Actually there is no minification on staging (turned on in production), so that will help matters considerably 😂

**Comment by CiaranChris** [comment]
Font stitch - Happy to wait this one out also. 

Accessibility - Let's turn it back on for mobile.

**Comment by briggySmalls** [comment]
How about the title on the slider, what do you think about revealing it on mobile?

**Comment by CiaranChris** [comment]
reveal away 🎊

**Comment by briggySmalls** [comment]
Cache-Control rules added to the nginx-includes seems to mess with jetpack's photon. Turning this off for the moment.
