### ISSUE TITLE
Add new Favicon

### ISSUE THREAD

**Issue by briggySmalls** [briggySmalls/skin-deep-server#95]
The site's favicon doesn't seem to be working.

**Comment by briggySmalls** [comment]
This was just because it wasn't configured in the admin.

@CiaranChris did you want to provide a new one?

**Comment by briggySmalls** [comment]
Should be a square size. If we want to use it to generate all sorts of icons (e.g. shortcut icons for iOS desktop) then i _think_ it needs to be a minimum of 310x310px

**Comment by CiaranChris** [comment]
![skin deep logo 2018_favicon-06](https://user-images.githubusercontent.com/29028655/49041368-f74d8b00-f1bc-11e8-8808-df47fc77cfc0.png)
